# 列表，yaml形式
#com:
#  saber:
#    url:
#      - http://wwww.baidu.com
#      - http://wwww.qq.com

# 列表，yaml形式，逗号分割
#com:
#  saber:
#    url: http://wwww.baidu.com,http://wwww.qq.com

# Map，yaml形式
#com:
#  saber:
#    map:
#      foo: bar
#      hello: world
# Map，yaml非字母数字和"-"，以[]括起来
#com:
#  saber:
#    map:
#      '[foo.baz]': bar